PREFIX eg: <http://www.example.org/>
CONSTRUCT {
  GRAPH ?g {
    ?s ?p ?o
  }
} {
  { SELECT * {
    GRAPH ?g {
      ?s
        ?p ?o ;
        eg:idx ?key
    }
    FILTER(ABS(FLOOR(?key * 0.5) - ?key * 0.5) < 0.1)
  } ORDER BY ?key ?g }
}

