#CONSTRUCT { ?s ?p ?o . GRAPH ?g { ?s ?p ?o } } {
#SELECT * {
INSERT { ?s ?p ?o }
WHERE {
    {
      SERVICE <triples.ttl> {
          { ?s ?p ?o }
        UNION 
          { GRAPH ?g { ?s ?p ?o } }
      }
    }
  UNION
    {
      SERVICE <quads.trig> {
          { ?s ?p ?o }
        UNION 
          { GRAPH ?g { ?s ?p ?o } }
      }
    }
}
