PREFIX s: <http://rdfs.org/ns/void#>

CONSTRUCT {
  <env://D> s:distinctIRIReferences ?x
} {
  SELECT
    (COUNT(DISTINCT ?u ) AS ?x)
  {
      { ?u ?p ?o }
    UNION
      { ?s ?u ?o }
    UNION
      { ?s ?p ?u }
    FILTER(isIri(?u))
  }
}